export const ActionTypes = {
  RENAME_USER: 'RENAME_USER',
  RECOLOR_USER: 'RECOLOR_USER',
  UPDATE_WIN_NUMBER: 'UPDATE_WIN_NUMBER',
  UPDATE_SCORE: 'UPDATE_SCORE',
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  ADD_BOX: 'ADD_BOX',
  ADD_PLACEHOLDER: 'ADD_PLACEHOLDER',
  JADGE_WINNER: 'JADGE_WINNER',
  REMATCH: 'REMATCH',
} as const
