export const MutationTypes = {
  UPDATE_USERS: 'UPDATE_USERS',
  UPDATE_SCORES: 'UPDATE_SCORES',
  UPDATE_ORDER: 'UPDATE_ORDER',
  UPDATE_WIN_NUMBER: 'UPDATE_WIN_NUMBER',
  ADD_BOX: 'ADD_BOX',
  ADD_PLACEHOLDER: 'ADD_PLACEHOLDER',
  ADD_HISTORY: 'ADD_HISTORY',
  REMOVE_HISTORY: 'REMOVE_HISTORY',
  UPDATE_HISTORY_INDEX: 'UPDATE_HISTORY_INDEX',
  UPDATE_WINNERS: 'UPDATE_WINNERS',
  RESTART: 'RESTART',
} as const
